// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgqwzalqpqjomacihgnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJncXd6YWxxcHFqb21hY2loZ251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMTUxNDQsImV4cCI6MjA2MDY5MTE0NH0.6sjjM1iHE3Qmq-ze-uXCzcMEW-4fNrvtAR1IpuPVeVQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);